#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "Running pre-commit hook"
echo 'Current branch: $(git branch --show-current)'
git branch --show-current > .gitbranch
echo "export const GIT_BRANCH = '$branch';" > ./src/git-info.js
